bash: Overhaul script up to current standard
Signed-off-by: Mark Grant <m.grant.prg@gmail.com>

diff --git a/src/prg/bash/gen-gnulib.sh.in b/src/prg/bash/gen-gnulib.sh.in
--- a/src/prg/bash/gen-gnulib.sh.in
+++ b/src/prg/bash/gen-gnulib.sh.in
@@ -1,4 +1,4 @@
-#! /usr/bin/env bash
+#! @bashlocation@
 #########################################################################
 #									#
 #	gen-gnulib.sh is automatically generated,			#
@@ -9,19 +9,39 @@
 #########################################################################
 #									#
 # Script ID: gen-gnulib.sh						#
-# Author: Copyright (C) 2018  Mark Grant				#
+# Author: Copyright (C) 2018, 2021  Mark Grant				#
 #									#
 # Released under the GPLv3 only.					#
 # SPDX-License-Identifier: GPL-3.0					#
 #									#
 # Purpose:								#
-# To perform initial gnulib setup for the project.			#
+# To simplify the running of daily apt-get maintenance commands.	#
 #									#
-# Syntax:	bootstrap.sh	[ -h || --help ] ||			#
-#				[ -V || --version ] ||			#
-#				[ Project root directory ]		#
-# Exit Codes:	0 - success						#
-#		1 - failure.						#
+# Syntax:	gen-gnulib.sh [ -h || --help ] || [ -V || --version ]	#
+#									#
+# Exit codes used:-							#
+# Bash standard Exit Codes:	0 - success				#
+#				1 - general failure			#
+# User-defined exit code range is 64 - 113				#
+#	C/C++ Semi-standard exit codes from sysexits.h range is 64 - 78	#
+#		EX_USAGE	64	command line usage error	#
+#		EX_DATAERR	65	data format error		#
+#		EX_NOINPUT	66	cannot open input		#
+#		EX_NOUSER	67	addressee unknown		#
+#		EX_NOHOST	68	host name unknown		#
+#		EX_UNAVAILABLE	69	service unavailable		#
+#		EX_SOFTWARE	70	internal software error		#
+#		EX_OSERR	71	system error (e.g., can't fork)	#
+#		EX_OSFILE	72	critical OS file missing	#
+#		EX_CANTCREAT	73	can't create (user) output file	#
+#		EX_IOERR	74	input/output error		#
+#		EX_TEMPFAIL	75	temp failure; user is invited	#
+#					to retry			#
+#		EX_PROTOCOL	76	remote error in protocol	#
+#		EX_NOPERM	77	permission denied		#
+#		EX_CONFIG	78	configuration error		#
+#	User-defined (here) exit codes range 79 - 113:			#
+#		None							#
 #									#
 # Further Info:								#
 #									#
@@ -34,15 +54,17 @@
 # Date		Author	Version	Description				#
 #									#
 # 07/02/2018	MG	1.0.1	Created.				#
+# 19/10/2021	MG	1.0.2	Major overhaul.				#
 #									#
 #########################################################################
+
 
 ##################
 # Init variables #
 ##################
-script_exit_code=0
-version="1.0.1"			# set version variable
-packageversion=@pkgversion@	# Version of the complete package
+readonly version=1.0.2				# Script version
+readonly outputprefix="$(basename $0): "
+readonly packageversion=@pkgversion@		# Package version
 
 basedir="."
 
@@ -51,99 +73,121 @@ basedir="."
 # Functions #
 #############
 
-# Output $1 to stdout or stderr depending on $2.
+# -h --help output.
+# No parameters
+# No return value
+usage ()
+{
+cat << EOF
+Usage is $0 [OPTIONS]
+	[OPTIONS] are:-
+	-h or --help Displays usage information
+	-V or --version Displays version information
+EOF
+}
+
+# Standard function to emit messages depending on various parameters.
+# Parameters -	$1 What:-	The message to emit.
+#		$2 Where:-	stdout == 0
+#				stderr == 1
+# No return value.
 output()
 {
-	if [ $2 = 0 ]
-	then
-		echo "$1"
+	if (( !$2 )); then
+		printf "%s\n" "$1"
 	else
-		echo "$1" 1>&2
+		printf "%s\n" "$1" 1>&2
 	fi
 }
 
-# Standard function to test command error ($1 is $?) and exit if non-zero
-std_cmd_err_handler()
-{
-	if [ $1 != 0 ]
-	then
-		script_exit_code=$1
-		script_exit
-	fi
-}
-
-# Standard function to cleanup and return exit code
+# Standard function to tidy up and return exit code.
+# Parameters - 	$1 is the exit code.
+# No return value.
 script_exit()
 {
-	exit $script_exit_code
+	exit $1
 }
 
-# Standard trap exit function
+# Standard function to test command error and exit if non-zero.
+# Parameters - 	$1 is the exit code, (normally $? from the preceeding command).
+# No return value.
+std_cmd_err_handler()
+{
+	if (( $1 )); then
+		script_exit $1
+	fi
+}
+
+# Standard trap exit function.
+# No parameters.
+# No return value.
 trap_exit()
 {
-script_exit_code=1
-output "Script terminating due to trap received." 1
-script_exit
+	local -i exit_code=$?
+	local msg
+
+	msg="Script terminating with exit code $exit_code due to trap received."
+	output "$msg" 1
+	script_exit $exit_code
 }
 
-# Setup trap
-trap trap_exit SIGHUP SIGINT SIGTERM
+# Setup trap.
+trap trap_exit SIGHUP SIGINT SIGQUIT SIGTERM
+
+# Process command line arguments with GNU getopt.
+# Parameters -	$1 is the command line.
+# No return value.
+proc_CL()
+{
+	local GETOPTTEMP
+	local tmpGETOPTTEMP
+
+	tmpGETOPTTEMP="getopt -o hV --long help,version"
+	GETOPTTEMP=$($tmpGETOPTTEMP -n "$0" -- "$@")
+	std_cmd_err_handler $?
+
+	eval set -- "$GETOPTTEMP"
+	std_cmd_err_handler $?
+
+	while true; do
+		case "$1" in
+		-h|--help)
+			usage
+			shift
+			script_exit 0
+			;;
+		-V|--version)
+			printf "Script version %s\n" $version
+			printf "Package version %s\n" $packageversion
+			shift
+			script_exit 0
+			;;
+		--)	shift
+			break
+			;;
+		*)	output "Internal error." 1
+			script_exit 64
+			;;
+		esac
+	done
+
+	# Pass anything after the -- straight to the commands.
+	if (( $# )); then
+		basedir=$@
+	fi
+}
 
 
 ########
 # Main #
 ########
-# Process command line arguments with GNU getopt.
-GETOPTTEMP=`getopt -o hV --long help,version -n "$0" -- "$@"`
-std_cmd_err_handler $?
 
-eval set -- "$GETOPTTEMP"
-std_cmd_err_handler $?
-
-while true
-do
-	case "$1" in
-	-h|--help)
-		echo "Usage is [ Option ] [ Project root directory ]:-"
-		echo "	-h or --help displays usage information"
-		echo "	-V or --version displays version information"
-		echo "	Project root directory, defaults to current directory."
-		shift
-		script_exit_code=0
-		script_exit
-		;;
-	-V|--version)
-		echo "$0 Script version "$version
-		echo "$0 Package version "$packageversion
-		shift
-		script_exit_code=0
-		script_exit
-		;;
-	--)	shift
-		break
-		;;
-	*)	script_exit_code=1
-		output "Internal error." 1
-		script_exit
-		;;
-	esac
-done
-
-# Script can accept 1 other argument, the base directory.
-if [ $# -gt 1 ]
-then
-	script_exit_code=1
-	output "Invalid argument." 1
-	script_exit
-fi
-
-if [ $# -eq 1 ]
-then
-	basedir=$1
-fi
-
+proc_CL "$@"
 
 gnulib-tool --import --dir=$basedir --source-base=src/prg/c/gen/lib \
 	--no-conditional-dependencies --no-libtool --no-vc-files configmake
-script_exit_code=$?
-script_exit
+status=$?
+std_cmd_err_handler $status
+
+script_exit 0
+
